INSERT INTO USERS VALUES (1, SYSDATE, FALSE, SYSDATE, 0, 'customer', 'CUSTOMER');
INSERT INTO USERS VALUES (2, SYSDATE, FALSE, SYSDATE, 0, 'admin', 'ADMIN');


INSERT INTO PRODUCT (DELETED,PRICE, PRODUCT_NAME) VALUES (0, 4, 'Product 0');
INSERT INTO PRODUCT (DELETED,PRICE, PRODUCT_NAME) VALUES (0, 5, 'Product 1');
INSERT INTO PRODUCT (DELETED,PRICE, PRODUCT_NAME) VALUES (0, 6, 'Product 2');
INSERT INTO PRODUCT (DELETED,PRICE, PRODUCT_NAME) VALUES (0, 3, 'Product 3');
INSERT INTO PRODUCT (DELETED,PRICE, PRODUCT_NAME) VALUES (0, 2, 'Product 4');
INSERT INTO PRODUCT (DELETED,PRICE, PRODUCT_NAME) VALUES (0, 3, 'Product 5');
INSERT INTO PRODUCT (DELETED,PRICE, PRODUCT_NAME) VALUES (0, 5, 'Product 6');
INSERT INTO PRODUCT (DELETED,PRICE, PRODUCT_NAME) VALUES (0, 2, 'Product 7');